import { StyleSheet } from 'react-native';
import { COLORS, SIZES } from '../colors';

export const profileStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.background,
  },
  // Стили для роли пользователя
  roleContainer: {
    alignItems: 'center',
    paddingHorizontal: SIZES.padding,
    paddingVertical: 20,
    backgroundColor: COLORS.white,
    marginBottom: 20,
    borderRadius: SIZES.borderRadius,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 3.84,
    elevation: 5,
  },
  roleBadge: {
    paddingHorizontal: 20,
    paddingVertical: 8,
    borderRadius: 20,
    marginBottom: 10,
  },
  roleContent: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  roleText: {
    color: COLORS.white,
    fontSize: 16,
    fontWeight: '600',
    textAlign: 'center',
    marginLeft: 8,
  },
  roleSubtitle: {
    fontSize: 14,
    color: COLORS.textSecondary,
    textAlign: 'center',
    fontWeight: '400',
  },
  scrollView: {
    flex: 1,
    paddingHorizontal: SIZES.padding,
    paddingTop: 10,
    paddingBottom: 100, // Место для BottomNavigation
  },
  bannerContainer: {
    position: 'relative',
    height: 200,
    borderRadius: SIZES.borderRadius,
    overflow: 'hidden',
    marginBottom: 30,
  },
  bannerImage: {
    width: '100%',
    height: '100%',
  },
  bannerAddButton: {
    position: 'absolute',
    top: 80,
    left: '50%',
    transform: [{ translateX: -50 }],
    backgroundColor: 'rgba(255, 255, 255, 0.9)',
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderRadius: SIZES.borderRadius,
  },
  bannerAddText: {
    fontSize: 14,
    fontWeight: '400',
    color: COLORS.text,
    textTransform: 'uppercase',
    textDecorationLine: 'underline',
  },
  profilePhotoContainer: {
    position: 'absolute',
    bottom: -40,
    left: 30,
    width: 80,
    height: 80,
    borderRadius: 40,
    borderWidth: 4,
    borderColor: COLORS.white,
    overflow: 'hidden',
  },
  profilePhoto: {
    width: '100%',
    height: '100%',
  },
  profilePhotoAddButton: {
    position: 'absolute',
    top: '50%',
    left: '50%',
    transform: [{ translateX: -40 }, { translateY: -10 }],
    backgroundColor: 'rgba(0, 0, 0, 0.7)',
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 4,
  },
  profilePhotoAddText: {
    fontSize: 10,
    fontWeight: '400',
    color: COLORS.white,
    textTransform: 'uppercase',
    textDecorationLine: 'underline',
  },
  statusesContainer: {
    flexDirection: 'column',
    gap: 25,
    marginBottom: 42,
  },
  statusCard: {
    backgroundColor: COLORS.white,
    borderRadius: SIZES.borderRadius,
    padding: 22,
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 200,
  },
  statusTitle: {
    fontSize: 48,
    fontWeight: '400',
    color: COLORS.text,
    textAlign: 'center',
    marginBottom: 15,
  },
  statusText: {
    fontSize: 18,
    fontWeight: '400',
    color: COLORS.text,
    textAlign: 'center',
  },
  statusIconContainer: {
    width: 48,
    height: 48,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 15,
  },
  statusActions: {
    flexDirection: 'row',
    gap: 15,
    marginTop: 15,
    width: '100%',
  },
  statusButtonPrimary: {
    flex: 1,
    backgroundColor: COLORS.primary,
    paddingVertical: 13,
    paddingHorizontal: 18,
    borderRadius: SIZES.borderRadius,
    alignItems: 'center',
  },
  statusButtonPrimaryText: {
    color: COLORS.white,
    fontSize: 12,
    fontWeight: '400',
  },
  statusButtonSecondary: {
    flex: 1,
    backgroundColor: COLORS.menuColor,
    paddingVertical: 13,
    paddingHorizontal: 18,
    borderRadius: SIZES.borderRadius,
    alignItems: 'center',
  },
  statusButtonSecondaryText: {
    color: COLORS.primary,
    fontSize: 12,
    fontWeight: '400',
  },
  section: {
    marginBottom: 42,
  },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 16,
    marginBottom: 30,
  },
  sectionIconContainer: {
    width: 32,
    height: 32,
    alignItems: 'center',
    justifyContent: 'center',
  },
  sectionTitle: {
    fontSize: 24,
    fontWeight: '400',
    color: COLORS.text,
  },
  formContainer: {
    gap: 12,
  },
  inputGroup: {
    gap: 8,
  },
  inputLabel: {
    fontSize: 14,
    fontWeight: '400',
    color: COLORS.text,
  },
  textInput: {
    backgroundColor: COLORS.white,
    borderWidth: 1,
    borderColor: '#E0E0E0',
    borderRadius: SIZES.borderRadius,
    paddingHorizontal: 16,
    paddingVertical: 12,
    fontSize: 16,
    color: COLORS.text,
  },
  actionsContainer: {
    marginBottom: 25,
  },
  saveButton: {
    backgroundColor: COLORS.primary,
    paddingVertical: 13,
    paddingHorizontal: 18,
    borderRadius: SIZES.borderRadius,
    alignItems: 'center',
    width: '100%',
  },
  saveButtonDisabled: {
    backgroundColor: '#ccc',
    opacity: 0.7,
  },
  saveButtonText: {
    color: COLORS.white,
    fontSize: 12,
    fontWeight: '400',
  },
  loadingOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(255, 255, 255, 0.8)',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 1000,
  },
  loadingText: {
    marginTop: 10,
    fontSize: 16,
    color: COLORS.text,
  },
  errorContainer: {
    backgroundColor: '#ffebee',
    padding: 15,
    margin: 10,
    borderRadius: SIZES.borderRadius,
    borderWidth: 1,
    borderColor: '#f44336',
  },
  errorText: {
    color: '#f44336',
    fontSize: 14,
    textAlign: 'center',
    marginBottom: 10,
  },
  demoText: {
    color: '#666',
    fontSize: 12,
    textAlign: 'center',
    marginBottom: 10,
    fontStyle: 'italic',
  },
  retryButton: {
    backgroundColor: COLORS.primary,
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderRadius: SIZES.borderRadius,
    alignSelf: 'center',
  },
  retryButtonText: {
    color: COLORS.white,
    fontSize: 12,
    fontWeight: '400',
  },
});
